### PR TITLE
Error code 500

### PR DESCRIPTION
**Pull request by StellarDoor5319**
Created a page for *500: Internal Server Error*. This makes it more descriptive than Apache's default page, and we get it reported to Rollbar.

---
This change is [Reviewable](https://reviewable.io/reviews/micathon3/zeus-web/66)

### CODE REVIEW

**Comment by StellarDoor5319** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.htaccess, line 2 at r1](https://reviewable.io:443/reviews/micathon3/zeus-web/66#-KuFtigE8xUnC311GeYR:-KuFtigFyhJaTnW6lohu:bnfp4nl) ([raw file](https://github.com/micathon3/zeus-web/blob/0ee56d09acbc676e8317f5bce319339df7d271c6/.htaccess#L2)):*
> ```
> ErrorDocument 404 http://www.kolechia.heliohost.org/micathon_zeus/site/404.php
> ErrorDocument 500 http://www.kolechia.heliohost.org/micathon_zeus/site/500.php
> ```

:lgtm:

---

*[500.php, line 40 at r1](https://reviewable.io:443/reviews/micathon3/zeus-web/66#-KuFtuTJlsz5soReLO-W:-KuFtuTJlsz5soReLO-X:b-eoys93) ([raw file](https://github.com/micathon3/zeus-web/blob/0ee56d09acbc676e8317f5bce319339df7d271c6/500.php#L40)):*
> ```PHP
> <h1>500</h1>
> <h2>It's not your fault...</h2>
> <p>The 500 error is normally caused when the server crashes, or something has been programmed incorrectly by us. This has been reported to the team and will, hopefully, be fixed soon.</p>
> ```

What to do next???

---

The user needs to know what to do next, for example:
- email support
- go back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-web/66)*

**Comment by StellarDoor5319** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-web/66)*

**Comment by TheSteelBarr** [comment]
kk m8

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-web/66#-:-KuP0GNvbvYekOKUl1OA:b-7nulyy)*

**Comment by TheSteelBarr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-web/66#-:-KwAGRXpqFd_fSez1qga:bnfp4nl)*

**Comment by TheSteelBarr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-web/66#-:-KwtgAFp6S6KQm5XuZMR:bnfp4nl)*

**Comment by StellarDoor5319** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[500.php, line 40 at r1](https://reviewable.io:443/reviews/micathon3/zeus-web/66#-KuFtuTJlsz5soReLO-W:-Kwxm2sKSWKxAOHLgJ_D:b-896fix) ([raw file](https://github.com/micathon3/zeus-web/blob/0ee56d09acbc676e8317f5bce319339df7d271c6/500.php#L40)):*
<details><summary><i>Previously, StellarDoor5319 (Daniel Thwaites) wrote…</i></summary><blockquote>

What to do next???

---

The user needs to know what to do next, for example:
- email support
- go back
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-web/66)*

**Comment by StellarDoor5319** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/micathon3/zeus-web/66)*

**Pull request merged**
